#### Sorting an 1D Array

In [1]:
import numpy as np

In [2]:
#Array1
arr1 = np.array([2,7,8,5,3,8,10])

In [3]:
arr1

array([ 2,  7,  8,  5,  3,  8, 10])

In [4]:
print("Array1 After Sorting: ",np.sort(arr1))

Array1 After Sorting:  [ 2  3  5  7  8  8 10]


In [5]:
#Array2
arr2 = np.array(['Apple','Litchi','Banana','Mango','Olive','Berry'])

In [6]:
arr2

array(['Apple', 'Litchi', 'Banana', 'Mango', 'Olive', 'Berry'],
      dtype='<U6')

In [8]:
print("Array2 After Sorting: ",np.sort(arr2))

Array2 After Sorting:  ['Apple' 'Banana' 'Berry' 'Litchi' 'Mango' 'Olive']


In [9]:
#Array3
#Sorting an Boolean Array

arr3 = np.array([True,False,False,True,False])

In [10]:
arr3

array([ True, False, False,  True, False])

In [12]:
print("Array3 after sorting: ",np.sort(arr3))

Array3 after sorting:  [False False False  True  True]


#### Sorting a 2D Array

In [14]:
#Creating a 2D Array

arr4 = np.array([[1,2,3],[5,2,8]])

In [15]:
arr4

array([[1, 2, 3],
       [5, 2, 8]])

In [17]:
print("2D Array4 After Sorting: \n",np.sort(arr4))

2D Array4 After Sorting: 
 [[1 2 3]
 [2 5 8]]
