In [ ]:
# Importing numpy libraries

import numpy as np

### Indexing

In [ ]:
# Creating an array

arr1 = np.array([1,2,3,4,5,6])

In [ ]:
arr1

array([1, 2, 3, 4, 5, 6])

In [ ]:
print(arr1)

[1 2 3 4 5 6]


In [ ]:
# Using index number we can access item inside array

print(arr1[0])
print(arr1[1])

1
2


In [ ]:
print(arr1[-3])

4


In [ ]:
#Creating another array using random function

arr2 = np.random.randint(1,10,size = (2,2),dtype = 'int')

In [ ]:
print(arr2)

[[8 5]
 [6 3]]


In [ ]:
print(arr2[0,0])
print(arr2[0,1])


8
5


In [ ]:
print(arr2[1,0])
print(arr2[1,1])

6
3


In [66]:
# Creating another array with size (3,3)

arr3 = np.random.randint(1,10,size = (3,3),dtype='int')

In [67]:
print(arr3)

[[8 1 1]
 [6 8 5]
 [7 2 9]]


In [69]:
print(arr3[0,0])
print(arr3[0,1])
print(arr3[0,2])

8
1
1


In [70]:
print(arr3[1,0])
print(arr3[1,1])
print(arr3[1,2])

6
8
5


In [71]:
print(arr3[2,0])
print(arr3[2,1])
print(arr3[2,2])

7
2
9


In [72]:
# Creatin another array with 3D (3 Diementional)

arr4 = np.random.randint(1,10,size=(2,3,3),dtype = 'int')

In [73]:
print(arr4)

[[[7 3 5]
  [8 1 8]
  [6 2 2]]

 [[3 6 9]
  [7 7 6]
  [4 6 4]]]


In [74]:
print(arr4[0,0,0])
print(arr4[0,0,1])
print(arr4[0,0,2])

7
3
5


In [75]:
print(arr4[0,1,0])
print(arr4[0,1,1])
print(arr4[0,1,2])

8
1
8


In [76]:
print(arr4[0,2,0])
print(arr4[0,2,1])
print(arr4[0,2,2])

6
2
2


In [77]:
print(arr4[1,0,0])
print(arr4[1,0,1])
print(arr4[1,0,2])

3
6
9


In [78]:
print(arr4[1,1,0])
print(arr4[1,1,1])
print(arr4[1,1,2])

7
7
6


In [79]:
print(arr4[1,2,0])
print(arr4[1,2,1])
print(arr4[1,2,2])

4
6
4


### Slicing

In [80]:
print(arr1)

[1 2 3 4 5 6]


In [81]:
print(arr1[0:3])

array([1, 2, 3])

In [82]:
print(arr1[2:])

[3 4 5 6]


In [83]:
#call arr2

print(arr2)

[[8 5]
 [6 3]]


In [86]:
arr2[0:1,:-1]

array([[8]])