In [ ]:
# Importing numpy libraries

import numpy as np

#### Manipulating: There are 5 way of manipulating Array shape

                   1. Reshape()
                   2. Resize()
                   3. Flatten()
                   4. Revel()
                   5. Defining Array Shape

In [88]:
# Reshape()

a = np.array(([1,2,3],
             [4,5,6]))

In [89]:
print(a)

[[1 2 3]
 [4 5 6]]


In [90]:
#Checking shape
a.shape

(2, 3)

In [92]:
#here reshaping

reshape = np.reshape(a,(3,2))

In [93]:
reshape

array([[1, 2],
       [3, 4],
       [5, 6]])

In [94]:
#Resize()

print(a)

[[1 2 3]
 [4 5 6]]


In [95]:
resized = np.resize(a,(4,3))

In [96]:
resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [99]:
# Ravel()

#creating array

arr = np.random.randint(1,10,size = (2,3),dtype = 'int')

In [100]:
arr

array([[3, 5, 7],
       [3, 2, 9]])

In [113]:
# using ravel function
# It convert any kind of array in 1D array
# Return a view of main array
a_raveled = np.ravel(arr)

In [114]:
a_raveled

array([8, 5, 7, 3, 2, 9])

In [110]:
a_raveled[0] = 8

In [111]:
a_raveled

array([8, 5, 7, 3, 2, 9])

In [112]:
arr

array([[8, 5, 7],
       [3, 2, 9]])

In [103]:
a_raveled.shape

(6,)

In [104]:
#Flatten()
print(arr)

[[3 5 7]
 [3 2 9]]


In [121]:
a_flateened = a.flatten() #Return a copy of array and always alocate a new memory

In [122]:
a_flateened

array([1, 2, 3, 4, 5, 6])

In [123]:
a_flateened[0] = 100

In [124]:
a_flateened

array([100,   2,   3,   4,   5,   6])

In [125]:
a 

#there is no change in array
#flatten cannot update index value like ravel instantly

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
#Defining a array shape

a

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
a.shape

(2, 3)

In [128]:
#given new shape

a.shape = (3,2)

In [129]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [130]:
print('Thank you')

Thank you
